name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Conan package manager
      run: |
           pwd
           pip3 install wheel setuptools
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           echo $PATH
           conan --version
           ls
           sudo ln -s ~/.local/bin/conan /usr/local/bin/conan

    - name: configure
      run: conan install . --build; cmake .
    - name: make
      run: make
    
