name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Download Conan package manager
      run: |
           pwd
           pip3 install wheel setuptools
           pip3 install conan
           export PATH=$PATH:/home/runner/.local/bin
           echo $PATH
           conan --version
           ls
           sudo ln -s ~/.local/bin/conan /usr/local/bin/conan

    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: cache-conan
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: /home/runner/.conan/
        key: theKey
        
    - name: configure
      run: conan install . --build; cmake .
    
   
      
    - name: make
      run: make
    
