name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: pip install conan
    - name: configure
      run: conan install . --build missing; cmake .
    - name: make
      run: make
    
